spring:
  profiles:
    active:
      - dev
---
#开发环境
spring:
  profiles: dev
  application:
    name: blog-config-dev
---
#测试环境
spring:
  profiles: test
  application:
    name: blog-config-test
#请保存为UTF-8格式
