spring:
  profiles:
    active:
    - dev
---
server:
  port: 9013 #注册中心占用7001端口,冒号后面必须要有空格

spring:
  profiles: dev
  application:
    name: blog-config-eureka

eureka:
  instance:
    hostname: localhost:9013 #冒号后面必须要有空格
  client:
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: http://localhost:9004/eureka/,http://localhost:9005/eureka/,http://localhost:9003/eureka/
---
server:
  port: 9013 #注册中心占用7001端口,冒号后面必须要有空格

spring:
  profiles: test
  application:
    name: blog-config-eureka

eureka:
  instance:
    hostname: localhost:9013 #冒号后面必须要有空格
  client:
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: http://localhost:9004/eureka/,http://localhost:9005/eureka/,http://localhost:9003/eureka/
