#server.port=8800
#spring.application.name=blog-config
#spring.cloud.config.server.git.uri=https://github.com/jean-zhou0512/springcloud-config.git
#//127.0.0.1:\u7AEF\u53E3/\u6587\u4EF6\u540D-?.\u6587\u4EF6\u540E\u7F00
#datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.url=jdbc:mysql://47.102.197.42:3306/mybatis
##Mapper\u6620\u5C04\u6587\u4EF6\u7684\u8DEF\u5F84
#mybatis.mapper-locations=classpath:Mapper/*.xml
##\u5F00\u542F\u9A7C\u5CF0\u547D\u540D\u6CD5
#mybatis.configuration.map-underscore-to-camel-case=true
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jean-zhou0512/springcloud-config.git
          #username:
          #password:
          search-paths:
  application:
    name: blog-config-git
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.102.197.42:3306/mybatis
server:
  port: 9500


